[package]
name = "kismesis-ssg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.16", features = ["derive"] }
kismesis = { version = "0.1.10" , features = ["plugins", "projects"]}

[profile.dev]
lto="off"
