
name: Rust

on:
  push:
    branches:
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/kismesis-ssg && mv target/release/kismesis-ssg target/release/kismesis-ssg_amd64

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: target/release/kismesis-ssg_amd64

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: win-build
          path: target/release/kismesis-ssg.exe

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --all --release && strip target/release/kismesis-ssg && mv target/release/kismesis-ssg target/release/kismesis-ssg_darwin

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-build
          path: target/release/kismesis-ssg_darwin
